[build]
  command = "yarn build"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[functions]
  included_files = ["!node_modules/hardhat/**/*", "!node_modules/hardhat-watcher/**/*", "!node_modules/@uniswap/widgets/**/*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
